### ISSUE TITLE
Replace lua-rapidjson with lua-cjson

### ISSUE THREAD

**Issue by mckaydavis** [KSDaemon/wiola#9]
I propose replacing the [lua-rapidjson](https://github.com/xpol/lua-rapidjson) package dependency with [lua-cjson](https://github.com/openresty/lua-cjson/).

Rationale:
* One less dependency when using [wiola](https://github.com/KSDaemon/wiola) within [OpenResty](https://github.com/openresty/openresty) as [lua-cjson is a default component in OpenResty](https://openresty.org/en/lua-cjson-library.html) -- while [lua-rapidjson](https://github.com/xpol/lua-rapidjson) is not.
* Furthermore, installing [lua-rapidjson](https://github.com/xpol/lua-rapidjson) via `luarocks install rapidjson` is further complicated as that requires a compiler and [CMake](https://github.com/Kitware/CMake) >= 3.0.0 to be installed to build `lua-rapidjson` from source. 
* Minor point, but the resulting `cjson.so` binary is 95% smaller than the `rapidjson.so` binary:
```
$ du -sb cjson.so rapidjson.so
132100	cjson.so
2444310	rapidjson.so
```
* For the API that wiola uses (i.e. `.encode` and `.decode`) it is a straight drop-in replacement with minimal code change. My preliminary testing after query-replacing all `require "rapidjson"` -> `require "cjson"` in [src/wiola/wiola.lua](src/wiola/wiola.lua) seems to work fine.

Thoughts?

**Comment by KSDaemon** [comment]
Hi @mckaydavis (again :) )
Well, in the begining i was using cjson, but than i had switched to rapidjson due to lack of support of empty arrays. In cjson you can globaly configure to encode lua empty tables as objects or as arrays. But wiola needs to encode different empty tables differently. 
I've got a look into open resty fork, and it has a `empty_array` and `empty_array_mt` things, which is good replacement for rapidjson `setmetatable({}, { __jsontype = 'object' })`
Will be great, if you can make a PR with that ;)

**Comment by KSDaemon** [comment]
And another one reason for using rapidjson — *cjson lacks support for big integers (> 32 bit)
